# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, this is coming from the code editor!
  displayName: 'Run a First script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
#- task: Bash@3
#      echo 'Hello world'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --image cool:latest'
  env: 
    SRCCLR_API_TOKEN: $(SRCCLR_API_TOKEN)
